### ISSUE TITLE
Class Object should have a nullable `name`

### ISSUE THREAD

**Issue by cuttlefish** [stac-extensions/label#7]
![image](https://user-images.githubusercontent.com/1152120/130209084-691049da-4db7-4894-a0ab-1c2ae84c7b1c.png)

https://github.com/stac-extensions/label/blob/3db3424b2b2e4e6acacd7833c106c079acfe24ba/json-schema/schema.json#L147

I'm attempting to add labels to a raster STAC Item using `pystac`.  It seems to be doing the correct thing by inserting a null for the Class Object `name` field. However it fails validation via the JSON Schema.

Am I misunderstanding how the label extension should be used or is this a bug in the schema?

**Comment by jisantuc** [comment]
Is `pystac` printing the field with a `null` value, or excluding it entirely from the rendered json?

**Comment by cuttlefish** [comment]
@jisantuc What sort of release cycle should I expect for the changes to the schema to go live?

**Comment by jisantuc** [comment]
I created the release a moment ago, though it's taking a minute for the schema url to cooperate

**Comment by cuttlefish** [comment]
@jisantuc Thanks so much! That saves me a bunch of work.
